apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume-input-claim
  name: volume-input-claim
spec:
  volumeName: "input-volume"
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume-model-claim
  name: volume-model-claim
spec:
  volumeName: "model-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume-archive-claim
  name: volume-archive-claim
spec:
  volumeName: "archive-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume-telemetry-claim
  name: volume-telemetry-claim
spec:
  volumeName: "telemetry-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume-outliers-claim
  name: volume-outliers-claim
spec:
  volumeName: "outliers-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
