apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-python
  name: ml-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-python
  template:
    metadata:
      labels:
        app: ml-python
    spec:
      containers:
        - env:
            - name: MODEL
              value: plant-disease-model-complete.pth
            - name: THRESHOLD
              value: "90"
          image: muhammadb/xbu-ml-python
          name: ml-python
          volumeMounts:
            - mountPath: /volumes/data/test/test
              name: volume-input-claim
            - mountPath: /volumes/model-store
              name: volume-model-claim
            - mountPath: /volumes/archive
              name: volume-archive-claim
            - mountPath: /volumes/telemetry
              name: volume-telemetry-claim
            - mountPath: /volumes/outliers
              name: volume-outliers-claim
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: volume-input-claim
          persistentVolumeClaim:
            claimName: volume-input-claim
        - name: volume-model-claim
          persistentVolumeClaim:
            claimName: volume-model-claim
        - name: volume-archive-claim
          persistentVolumeClaim:
            claimName: volume-archive-claim
        - name: volume-telemetry-claim
          persistentVolumeClaim:
            claimName: volume-telemetry-claim
        - name: volume-outliers-claim
          persistentVolumeClaim:
            claimName: volume-outliers-claim
