apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume_input_claim
  name: volume_input_claim
spec:
  volumeName: "inputvolume"
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume_model_claim
  name: volume_model_claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume_archive_claim
  name: volume_archive_claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume_telemetry_claim
  name: volume_telemetry_claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: volume_outliers_claim
  name: volume_outliers_claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
